version: '3.9'
services:
  frontend:
    build: ./client
    ports:
      - "80:80"
  backend:
    build: ./server
    ports:
      - "3001:3001"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"